# Generated by Django 4.1.2 on 2022-12-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_followrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='following',
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='actor',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='followrequest',
            name='object',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='author',
            name='following',
            field=models.JSONField(default=list),
        ),
    ]
