# Generated by Django 4.1.2 on 2022-10-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('author', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('items', models.JSONField(default=[])),
            ],
        ),
    ]
