# Generated by Django 4.1.2 on 2022-10-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('author', models.JSONField()),
                ('comment', models.CharField(max_length=200)),
                ('published', models.DateTimeField()),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('contentType', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('author', models.JSONField()),
                ('categories', models.JSONField()),
                ('count', models.IntegerField()),
                ('comments', models.CharField(max_length=200)),
                ('published', models.DateTimeField()),
                ('visibility', models.CharField(max_length=200)),
                ('unlisted', models.BooleanField()),
            ],
        ),
    ]
