# Generated by Django 4.1.2 on 2022-10-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
