# Generated by Django 4.1.2 on 2022-10-26 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_user_author_verified'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comments',
            name='size',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authors.author'),
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comments',
        ),
        migrations.AlterField(
            model_name='post',
            name='commentsSrc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_post', to='posts.comments'),
        ),
        migrations.AddField(
            model_name='comments',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.comment'),
        ),
    ]
