# Generated by Django 4.1.2 on 2022-10-24 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commentsSrc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_post', to='posts.comments'),
        ),
    ]
