# Generated by Django 4.1.2 on 2022-10-25 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('posts', '0003_alter_post_commentssrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authors.author'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.comment'),
        ),
        migrations.AlterField(
            model_name='post',
            name='commentsSrc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_post', to='posts.comments'),
        ),
    ]
