# Generated by Django 4.1.2 on 2022-10-28 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_post_commentssrc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='commentsSrc',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_post', to='posts.comments'),
        ),
    ]
