# Generated by Django 4.1.2 on 2022-10-25 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_comment_author_alter_comments_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comments',
            name='size',
            field=models.IntegerField(default=5),
        ),
    ]
