# Generated by Django 4.1.2 on 2022-11-16 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
        ('posts', '0004_alter_post_commentssrc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
                ('object', models.URLField(max_length=250)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
            ],
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.CharField(choices=[('text/markdown', 'markdown'), ('text/plain', 'plain text'), ('application/base64', 'application/base64'), ('image/png;base64', 'png'), ('image/jpeg;base64', 'jpeg')], default='text/plain', max_length=50),
        ),
        migrations.DeleteModel(
            name='LikeComment',
        ),
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
