# Generated by Django 4.1.2 on 2022-11-19 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_like_remove_likepost_author_alter_post_contenttype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='page',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='size',
        ),
    ]
