# Generated by Django 4.1.2 on 2022-10-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comments_page_comments_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='posts.comment'),
        ),
    ]
