# Generated by Django 4.1.2 on 2022-10-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_comments_comments_comments_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.ManyToManyField(blank=True, to='posts.comment'),
        ),
    ]
