# Generated by Django 4.1.2 on 2022-10-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_comments_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comments',
            field=models.ManyToManyField(blank=True, default=None, to='posts.comment'),
        ),
    ]
